import { StyleSheet } from 'react-native';

  export const styles = StyleSheet.create({
    root: {},
    card: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 10,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: 'bold',
    },
    manageBtn: {
      borderWidth: 1,
      borderColor: '#d9d9d9',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: '#f6f6f6',
    },
    manageBtnText: {
      fontSize: 13,
      fontWeight: '600',
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: '#666',
      marginBottom: 10,
      marginTop: 14,
      textTransform: 'uppercase',
    },
    listItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: '#e5e5e5',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 14,
      marginBottom: 10,
      minHeight: 52,
    },
    listItemPoolActive: {
      backgroundColor: '#fffaef',
      borderColor: '#f0c36b',
    },
    listItemSingleActive: {
      backgroundColor: '#f3f8ff',
      borderColor: '#d0e2ff',
    },
    listItemText: {
      fontSize: 15,
      fontWeight: '600',
      flex: 1,
      marginRight: 8,
    },
    confirmBtn: {
      marginTop: 12,
      backgroundColor: '#8BC34A',
      borderRadius: 8,
      paddingVertical: 14,
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 8,
    },
    confirmBtnText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 14,
    },
    manageCard: {
      padding: 0,
      marginTop: 0,
    },
    poolCard: {
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 8,
      padding: 10,
      marginBottom: 10,
    },
    poolHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    poolNameInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 6,
      paddingHorizontal: 10,
      paddingVertical: 10,
      fontSize: 15,
      fontWeight: '600',
      minHeight: 44,
    },
    poolLocations: {
      marginBottom: 8,
    },
    poolLocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 4,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    addMoreRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      gap: 8,
      minHeight: 44,
    },
    addMoreText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#666',
    },
    selectedLocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#f0f8ff',
      borderLeftWidth: 3,
      borderLeftColor: '#d0e2ff',
      paddingHorizontal: 10,
      paddingVertical: 12,
      marginBottom: 8,
      borderRadius: 6,
      minHeight: 56,
    },
    selectedLocationRowActive: {
      backgroundColor: '#e0f0ff',
      borderLeftColor: '#8BC34A',
    },
    selectedLocationLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 8,
    },
    selectedLocationText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#333',
      flex: 1,
    },
    selectedLocationSubText: {
      fontSize: 13,
      color: '#666',
      marginTop: 3,
    },
    platformCard: {
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: '#e0e0e0',
      borderRadius: 10,
      padding: 10,
      marginTop: 8,
      marginBottom: 6,
    },
    platformCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    platformCardHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    platformCardHeaderText: {
      fontSize: 15,
      fontWeight: '600',
      color: '#333',
      flex: 1,
      marginRight: 8,
    },
    platformLocationSelectRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 10,
      marginTop: 2,
    },
    platformLocationSelectText: {
      fontSize: 14,
      color: '#333',
      flex: 1,
      marginRight: 8,
    },
    platformSelectButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 6,
      marginBottom: 8,
      gap: 10,
      minHeight: 48,
    },
    platformSelectText: {
      fontSize: 14,
      fontWeight: '500',
      color: '#333',
      flex: 1,
    },
    dropdownContainer: {
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 6,
      backgroundColor: '#fff',
      overflow: 'hidden',
    },
    dropdownItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
      minHeight: 52,
    },
    dropdownItemText: {
      fontSize: 14,
      fontWeight: '500',
      color: '#333',
      flex: 1,
      marginRight: 8,
    },
    dropdownItemTimezone: {
      fontSize: 12,
      color: '#999',
      marginTop: 4,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      padding: 16,
    },
    modalCard: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 16,
      maxHeight: '88%',
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: 'bold',
    },
    tabsRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 12,
      marginBottom: 12,
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
      paddingVertical: 16,
      borderRadius: 8,
      borderWidth: 1,
      borderStyle: 'dashed',
    },
    tabGhost: {
      borderColor: '#d9d9d9',
      backgroundColor: '#fafafa',
    },
    tabActive: {
      borderColor: '#f0c36b',
      backgroundColor: '#fff5db',
    },
    tabText: {
      fontSize: 13,
      fontWeight: '600',
    },
    tabTextActive: {
      color: '#b8860b',
    },
    inputGroup: {
      marginBottom: 12,
    },
    label: {
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
      color: '#333',
    },
    textInput: {
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 8,
      padding: 12,
      fontSize: 15,
      minHeight: 48,
    },
    connRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: '#eee',
    },
    connLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flex: 1,
    },
    connName: {
      fontSize: 14,
      fontWeight: '600',
    },
    comboShell: {
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 8,
      paddingVertical: 8,
      paddingHorizontal: 8,
    },
    inlineChipsRow: {
      alignItems: 'center',
    },
    chip: {
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 6,
      marginRight: 8,
      backgroundColor: '#fafafa',
    },
    chipSelected: {
      borderColor: '#8BC34A',
      backgroundColor: '#8BC34A20',
    },
    chipText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#555',
    },
    chipTextSelected: {
      color: '#4CAF50',
    },
    addAnotherRow: {
      marginTop: 12,
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: '#ddd',
      borderRadius: 8,
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    addAnotherText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#666',
    },
    footerRow: {
      flexDirection: 'column',
      gap: 12,
      paddingTop: 12,
      marginTop: 8,
      color: 'white',
    },
    dropZone: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#f0f8f0',
      borderWidth: 2,
      borderStyle: 'dashed',
      borderColor: '#8BC34A',
      borderRadius: 8,
      padding: 16,
      marginTop: 8,
      gap: 8,
    },
    dropZoneText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#8BC34A',
    },
    reauthButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 4,
      paddingVertical: 6,
      paddingHorizontal: 10,
      backgroundColor: '#f0f8f0',
      borderRadius: 6,
      alignSelf: 'flex-start',
    },
    reauthButtonText: {
      fontSize: 12,
      fontWeight: '600',
      color: '#8BC34A',
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 40,
      paddingHorizontal: 20,
    },
    emptyStateTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#333',
      marginTop: 16,
      marginBottom: 8,
    },
    emptyStateSubtitle: {
      fontSize: 14,
      color: '#999',
      marginTop: 8,
      maxWidth: 300,
      textAlign: 'center',
      lineHeight: 20,
    },
    backBtn: {
      marginRight: 10,
      padding: 4,
    },
    input: {
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 8,
      padding: 12,
      fontSize: 15,
    },
    primaryBtn: {
      backgroundColor: '#8BC34A',
      borderRadius: 8,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    primaryBtnText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 15,
    },
    secondaryBtn: {
      backgroundColor: '#f0f0f0',
      borderRadius: 8,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
    },
    sectionTitle: { // Ensure this exists or override it to match design
      fontSize: 12,
      fontWeight: '700',
      color: '#999',
      marginTop: 20,
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    accordionContainer: {
      backgroundColor: '#fff',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#e0e0e0', // matches design "Closed - Default" look
      marginBottom: 8,
      overflow: 'hidden',
    },
    accordionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      minHeight: 56,
    },
    accordionHeaderOpen: {
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    accordionHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      gap: 8, // space between title and badge
    },
    accordionHeaderRight: {
      marginLeft: 12,
      flexDirection: 'row',
      alignItems: 'center',
    },
    accordionTitle: {
      fontSize: 16,
      fontWeight: '500',
      color: '#111',
    },
    accordionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    accordionBadgeText: {
      fontSize: 16,
      fontWeight: '500',
      color: '#111',
      marginRight: 6,
    },
    accordionIcons: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    accordionContent: {
      backgroundColor: '#fff',
    },
    accordionItemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    accordionItemText: {
      fontSize: 15,
      color: '#333',
    },
    singleLocationRow: { // For single locations in the main list
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
    },
  });
