// VENDORED - DO NOT EDIT.
// Backend source: ../sssync-bknd/src/contracts/product-patch.contract.ts
// Regenerate upstream with `npm run contracts:generate` from the backend root, then re-copy it here.
// @generated by scripts/generate-product-contract.mjs from scripts/product-contract.manifest.mjs.
// DO NOT EDIT. Change the manifest, then run `npm run contracts:generate`.

export const PRODUCT_PATCH_CONTRACT_VERSION = 2 as const;

export const PRODUCT_VARIANT_TYPES = ["flat","base","option"] as const;
export type ProductVariantType = (typeof PRODUCT_VARIANT_TYPES)[number];

export const PRODUCT_PARENT_PATCH_FIELDS = [
  "Title",
  "Description",
  "Vendor",
  "ProductType",
  "Brand",
  "Tags",
  "CategoryHint",
  "SeoTitle",
  "SeoDescription",
] as const;
export type ProductParentPatchField = (typeof PRODUCT_PARENT_PATCH_FIELDS)[number];

export const PRODUCT_VARIANT_PATCH_FIELDS = [
  "Sku",
  "Barcode",
  "Title",
  "Options",
  "VariantType",
  "Price",
  "CompareAtPrice",
  "Currency",
  "Weight",
  "WeightUnit",
  "Condition",
  "Mpn",
  "Gtin",
  "RequiresShipping",
  "IsTaxable",
  "TaxCode",
  "RecognitionStatus",
  "OriginPlatform",
] as const;
export type ProductVariantPatchField = (typeof PRODUCT_VARIANT_PATCH_FIELDS)[number];

export interface ProductParentPatch {
  Title?: string;
  Description?: string | null;
  Vendor?: string | null;
  ProductType?: string | null;
  Brand?: string | null;
  Tags?: string[];
  CategoryHint?: string | null;
  SeoTitle?: string | null;
  SeoDescription?: string | null;
}

export interface ProductVariantPatch {
  Sku?: string;
  Barcode?: string | null;
  Title?: string;
  Options?: Record<string, string> | null;
  VariantType?: ProductVariantType;
  Price?: number;
  CompareAtPrice?: number | null;
  Currency?: string;
  Weight?: number | null;
  WeightUnit?: string | null;
  Condition?: string | null;
  Mpn?: string | null;
  Gtin?: string | null;
  RequiresShipping?: boolean | null;
  IsTaxable?: boolean | null;
  TaxCode?: string | null;
  RecognitionStatus?: string | null;
  OriginPlatform?: string | null;
}

export interface ProductPatch {
  parent?: ProductParentPatch;
  variant?: ProductVariantPatch;
}

export const PRODUCT_MEDIA_TYPES = ["image","video"] as const;
export type ProductMediaType = (typeof PRODUCT_MEDIA_TYPES)[number];

export const PRODUCT_MEDIA_PROCESSING_STATUSES = ["pending","ready","failed"] as const;
export type ProductMediaProcessingStatus = (typeof PRODUCT_MEDIA_PROCESSING_STATUSES)[number];

export interface ProductMediaSetItem {
  MediaType: ProductMediaType;
  MediaUrl?: string | null;
  AltText?: string | null;
  ThumbnailUrl?: string | null;
  DurationSeconds?: number | null;
  ExternalId?: string | null;
  ProcessingStatus?: ProductMediaProcessingStatus | null;
}

export const PRODUCT_EDITABILITY_MANIFEST = {
  contractVersion: 2,
  parent: {
    Title: {
      group: "parent",
      nullable: false,
      editability: "direct",
    },
    Description: {
      group: "parent",
      nullable: true,
      editability: "direct",
    },
    Vendor: {
      group: "parent",
      nullable: true,
      editability: "direct",
    },
    ProductType: {
      group: "parent",
      nullable: true,
      editability: "direct",
    },
    Brand: {
      group: "parent",
      nullable: true,
      editability: "direct",
    },
    Tags: {
      group: "parent",
      nullable: false,
      editability: "direct",
    },
    CategoryHint: {
      group: "parent",
      nullable: true,
      editability: "direct",
    },
    SeoTitle: {
      group: "parent",
      nullable: true,
      editability: "direct",
    },
    SeoDescription: {
      group: "parent",
      nullable: true,
      editability: "direct",
    },
  },
  variant: {
    Sku: {
      group: "identity",
      nullable: false,
      editability: "direct",
    },
    Barcode: {
      group: "identity",
      nullable: true,
      editability: "direct",
    },
    Title: {
      group: "identity",
      nullable: false,
      editability: "conditional",
      rule: "Caller-set only for option variants. Flat and base titles are derived from the parent Title.",
    },
    Options: {
      group: "identity",
      nullable: true,
      editability: "direct",
    },
    VariantType: {
      group: "identity",
      nullable: false,
      editability: "transition",
      rule: "Transitions must match the final Options shape and the product sibling shape.",
    },
    Price: {
      group: "commerce",
      nullable: false,
      editability: "direct",
    },
    CompareAtPrice: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    Currency: {
      group: "commerce",
      nullable: false,
      editability: "direct",
    },
    Weight: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    WeightUnit: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    Condition: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    Mpn: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    Gtin: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    RequiresShipping: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    IsTaxable: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    TaxCode: {
      group: "commerce",
      nullable: true,
      editability: "direct",
    },
    RecognitionStatus: {
      group: "identity",
      nullable: true,
      editability: "direct",
    },
    OriginPlatform: {
      group: "identity",
      nullable: true,
      editability: "direct",
    },
  },
  media: {
    ProductMedia: {
      group: "media",
      editability: "set",
      command: "setProductMedia",
      rule: "The ordered mixed-media list is authoritative. PrimaryImageUrl is the first image entry; videos are never promoted to primary image.",
    },
  },
} as const;
